apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: javajava-java-sample-d6ht
  namespace: e2e-demos-ylit-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:34a6eebb977620c0d176d22495fad6fecdffb35a1d7529931c140552f6fd7d51
        name: my-java-springboot
        resources: {}
status: {}
